// The actual matching algorithm. This is the only place match scores come
// from — data/matches.json and data/intro_packets.json are generated by
// running this against the real startup and company data (see
// generate-data.js), not hand-typed. Re-run the generator any time
// data/startups.json or data/companies.json changes.

const WEIGHTS = {
  industry: 40,
  priority: 35,
  bizModel: 10,
  region: 15,
};

function getIndustryText(startup) {
  return [startup.company_industries, startup.company_sub_industries, startup.icp_industry, startup.company_all_tags]
    .filter(Boolean)
    .join(" | ")
    .toLowerCase();
}

function getDescText(startup) {
  return [startup.plain_english_description, startup.value_proposition, startup.icp_buyer_persona]
    .filter(Boolean)
    .join(" | ")
    .toLowerCase();
}

function keywordHits(text, keywords) {
  return keywords.filter((k) => text.includes(k.toLowerCase()));
}

function bizModelPoints(businessModel) {
  const m = (businessModel || "").toLowerCase();
  if (m.includes("saas")) return { points: WEIGHTS.bizModel, label: "SaaS (low-integration-effort pilot)" };
  if (m.includes("manufactur")) return { points: WEIGHTS.bizModel * 0.7, label: "Manufacturing" };
  if (m.includes("marketplace")) return { points: WEIGHTS.bizModel * 0.5, label: "Marketplace & ecommerce" };
  if (!m) return { points: WEIGHTS.bizModel * 0.3, label: "Not reported" };
  return { points: WEIGHTS.bizModel * 0.3, label: businessModel };
}

function regionPoints(startup, company) {
  const text = (startup.company_city || "").toLowerCase();
  const companyCity = (company.city || "").toLowerCase();
  const isWNY = /buffalo|niagara|east aurora|amherst|tonawanda|lackawanna|cheektowaga|williamsville/.test(text);
  if (text && companyCity && text.includes(companyCity)) {
    return { points: WEIGHTS.region, label: `Same city as ${company.name} (${startup.company_city})` };
  }
  if (isWNY) {
    return { points: WEIGHTS.region * 0.7, label: `Same WNY region (${startup.company_city})` };
  }
  return { points: 0, label: startup.company_city ? `Different region (${startup.company_city})` : "Region not reported" };
}

function statusMultiplier(status) {
  const s = (status || "").toLowerCase();
  if (s.includes("defunct")) return { factor: 0.05, label: status };
  if (s.includes("merged") || s.includes("acquired")) return { factor: 0.6, label: status };
  if (s.includes("inactive")) return { factor: 0.3, label: status };
  return { factor: 1, label: status || "Unknown" };
}

function recommendationFor(total, statusFactor) {
  if (statusFactor <= 0.1) return "Low priority";
  if (total >= 65) return "Strong match";
  if (total >= 45) return "Promising match";
  if (total >= 25) return "Worth investigating";
  return "Low priority";
}

function scoreStartup(startup, company) {
  const industryHits = keywordHits(getIndustryText(startup), company.target_industries);
  const priorityHits = keywordHits(getDescText(startup), company.priority_keywords);

  const industryScore = Math.min(1, industryHits.length / 3) * WEIGHTS.industry;
  const priorityScore = Math.min(1, priorityHits.length / 3) * WEIGHTS.priority;
  const biz = bizModelPoints(startup.company_business_model);
  const region = regionPoints(startup, company);
  const status = statusMultiplier(startup.current_status);

  const rawTotal = industryScore + priorityScore + biz.points + region.points;
  const total = Math.max(0, Math.min(100, Math.round(rawTotal * status.factor)));

  return {
    total,
    recommendation: recommendationFor(total, status.factor),
    breakdown: {
      industryHits,
      industryScore: Math.round(industryScore),
      priorityHits,
      priorityScore: Math.round(priorityScore),
      bizModelLabel: biz.label,
      bizModelScore: Math.round(biz.points),
      regionLabel: region.label,
      regionScore: Math.round(region.points),
      statusLabel: status.label,
      statusFactor: status.factor,
    },
  };
}

function buildMatchReasons(company, breakdown) {
  const reasons = [];
  if (breakdown.industryHits.length) {
    reasons.push(`Industry/product overlap with ${company.name}'s target sectors: ${breakdown.industryHits.join(", ")}.`);
  }
  if (breakdown.priorityHits.length) {
    reasons.push(`Description and value proposition touch on ${company.name}'s stated 2026 priorities: ${breakdown.priorityHits.join(", ")}.`);
  }
  if (breakdown.regionScore > 0) {
    reasons.push(`${breakdown.regionLabel} — lowers relationship friction for a first conversation.`);
  }
  if (breakdown.bizModelScore >= 7) {
    reasons.push(`Business model: ${breakdown.bizModelLabel}.`);
  }
  if (!reasons.length) {
    reasons.push("No meaningful overlap found in industry keywords, stated priorities, business model, or region — this pairing has little concrete basis.");
  }
  return reasons;
}

function buildRisks(startup, company, breakdown) {
  const risks = ["No named contact in the data — targeting a department, not a person."];
  if (breakdown.statusFactor < 1) {
    risks.push(`Current status is listed as "${breakdown.statusLabel}" — verify the company is still operating independently before an intro.`);
  }
  const emp = startup.latest_employees;
  if (emp === null || emp === undefined) {
    risks.push("Employee count not reported — team size and enterprise readiness are unknown.");
  } else if (emp < 5) {
    risks.push(`Very small team (${emp} employees) — enterprise readiness for ${company.name} is unconfirmed.`);
  }
  if (!breakdown.industryHits.length && !breakdown.priorityHits.length) {
    risks.push("This match was surfaced mainly by region/business-model factors rather than a specific industry or stated-priority match — treat as low-confidence.");
  }
  return risks;
}

function recommendedContactFor(company, breakdown, contactProfile) {
  const keyHit = breakdown.industryHits[0] || breakdown.priorityHits[0];
  const found = keyHit && contactProfile ? contactProfile.contacts.find((c) => c.theme === keyHit) : null;
  if (found) {
    return `No named contact in the data. Best entry point based on the matched theme (“${keyHit}”): ${company.name}'s ${found.department} team.`;
  }
  const fallback = contactProfile ? contactProfile.fallback_department : "Business Development / Partnerships";
  return `No named contact in the data, and no strong matched theme to target a specific department — recommend routing through ${company.name}'s ${fallback} team.`;
}

function introPacketFor(startup, company, score) {
  const b = score.breakdown;
  const isSkip = score.recommendation === "Low priority";
  const topTheme = b.industryHits[0] || b.priorityHits[0];

  const introAngle = isSkip
    ? "Not applicable."
    : topTheme
      ? `Lead with the shared theme of "${topTheme}" — connect it directly to ${company.name}'s stated 2026 priorities.`
      : `No strong shared theme was found automatically — confirm relevance with ${company.name} before framing an angle.`;

  const draftEmail = isSkip
    ? { subject: "", body: "" }
    : {
        subject: `43North intro: ${startup.company_name} x ${company.name}`,
        body: `Hi [Name],\n\nWanted to flag ${startup.company_name}, a company in the 43North ecosystem. ${startup.value_proposition || startup.plain_english_description || ""}\n\nGiven ${company.name}'s focus on ${topTheme || "your current priorities"}, this seemed worth a look.\n\nWould you be open to a 20-minute call to see if there's a fit?\n\nBest,\n[43North staff name]`,
      };

  return {
    value_prop: startup.value_proposition || startup.plain_english_description || "Not reported.",
    intro_angle: introAngle,
    draft_email: draftEmail,
    cta: isSkip ? "Not applicable." : "Would you be open to a 20-minute intro call?",
  };
}

module.exports = {
  scoreStartup,
  buildMatchReasons,
  buildRisks,
  recommendedContactFor,
  introPacketFor,
};
